// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using P_Asignación_de_Tareas.Models;

#nullable disable

namespace P_Asignación_de_Tareas.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    partial class ApplicationDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.AuxiliarT", b =>
                {
                    b.Property<int>("idAuxiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAuxiliar"));

                    b.Property<int>("idCommet")
                        .HasColumnType("integer");

                    b.Property<int>("idNotification")
                        .HasColumnType("integer");

                    b.Property<int>("idProyect")
                        .HasColumnType("integer");

                    b.Property<int>("idUser")
                        .HasColumnType("integer");

                    b.HasKey("idAuxiliar");

                    b.HasIndex("idCommet");

                    b.HasIndex("idNotification");

                    b.HasIndex("idProyect");

                    b.HasIndex("idUser");

                    b.ToTable("auxiliarT", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Comments", b =>
                {
                    b.Property<int>("idComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idComment"));

                    b.Property<string>("descriptionCommet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idComment");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Module", b =>
                {
                    b.Property<int>("IdMod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMod"));

                    b.Property<string>("NameMod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMod");

                    b.ToTable("module", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Notifications", b =>
                {
                    b.Property<int>("idNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idNotification"));

                    b.Property<string>("descriptionNotification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nameNotification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idNotification");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Operaciones", b =>
                {
                    b.Property<int>("IdRolpOperation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRolpOperation"));

                    b.Property<int>("IdOperaciones")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdRolpOperation");

                    b.HasIndex("IdOperaciones");

                    b.HasIndex("IdRol");

                    b.ToTable("operaciones", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Operations_Rol", b =>
                {
                    b.Property<int>("IdOperationsRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOperationsRol"));

                    b.Property<int>("IdModulo")
                        .HasColumnType("integer");

                    b.Property<string>("NameOperationRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdOperationsRol");

                    b.HasIndex("IdModulo");

                    b.ToTable("operation_rol", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Proyects", b =>
                {
                    b.Property<int>("idProyect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idProyect"));

                    b.Property<int>("idTasks")
                        .HasColumnType("integer");

                    b.Property<string>("nameProyect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idProyect");

                    b.HasIndex("idTasks");

                    b.ToTable("proyects", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Tasks", b =>
                {
                    b.Property<int>("idTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTask"));

                    b.Property<DateTime>("dateTask")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateTaskCompletion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descriptionTask")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nameTask")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idTask");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Users", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUser"));

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("emailUser")
                        .HasColumnType("text");

                    b.Property<string>("nameUser")
                        .HasColumnType("text");

                    b.Property<int>("password")
                        .HasColumnType("integer");

                    b.HasKey("idUser");

                    b.HasIndex("IdRol");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.AuxiliarT", b =>
                {
                    b.HasOne("P_Asignación_de_Tareas.Models.Comments", null)
                        .WithMany("AuxiliarT")
                        .HasForeignKey("idCommet");

                    b.HasOne("P_Asignación_de_Tareas.Models.Notifications", null)
                        .WithMany("AuxiliarT")
                        .HasForeignKey("idNotification");

                    b.HasOne("P_Asignación_de_Tareas.Models.Proyects", null)
                        .WithMany("AuxiliarT")
                        .HasForeignKey("idProyect");

                    b.HasOne("P_Asignación_de_Tareas.Models.Users", null)
                        .WithMany("AuxiliarT")
                        .HasForeignKey("idUser");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Operaciones", b =>
                {
                    b.HasOne("P_Asignación_de_Tareas.Models.Operations_Rol", null)
                        .WithMany("Operaciones")
                        .HasForeignKey("IdOperaciones");

                    b.HasOne("P_Asignación_de_Tareas.Models.Rol", null)
                        .WithMany("Rolope")
                        .HasForeignKey("IdRol");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Operations_Rol", b =>
                {
                    b.HasOne("P_Asignación_de_Tareas.Models.Module", null)
                        .WithMany("OperationsRol")
                        .HasForeignKey("IdModulo");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Proyects", b =>
                {
                    b.HasOne("P_Asignación_de_Tareas.Models.Tasks", null)
                        .WithMany("Proyects")
                        .HasForeignKey("idTasks");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Users", b =>
                {
                    b.HasOne("P_Asignación_de_Tareas.Models.Rol", null)
                        .WithMany("Users")
                        .HasForeignKey("IdRol");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Comments", b =>
                {
                    b.Navigation("AuxiliarT");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Module", b =>
                {
                    b.Navigation("OperationsRol");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Notifications", b =>
                {
                    b.Navigation("AuxiliarT");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Operations_Rol", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Proyects", b =>
                {
                    b.Navigation("AuxiliarT");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Rol", b =>
                {
                    b.Navigation("Rolope");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Tasks", b =>
                {
                    b.Navigation("Proyects");
                });

            modelBuilder.Entity("P_Asignación_de_Tareas.Models.Users", b =>
                {
                    b.Navigation("AuxiliarT");
                });
#pragma warning restore 612, 618
        }
    }
}
